version: "3.9"

services:
  backend:
    build: ./backend
    container_name: jobtrack-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: jobtrack-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
